# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sheeps_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('option', models.CharField(max_length=6)),
            ],
        ),
    ]
