# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellofsheep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheeps_table',
            name='application',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sheeps_table',
            name='ip',
            field=models.URLField(max_length=30),
        ),
    ]
